
services:
###> doctrine/doctrine-bundle ###
  database:
    image: mysql:${MYSQL_VERSION:-8.0}
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
      # You should definitely change the password in production
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-!ChangeMe!}
      MYSQL_USER: ${MYSQL_USER:-app}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-!ChangeMe!}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/mysql:rw
    ports:
      - "3307:3306"
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/mysql:rw
###< doctrine/doctrine-bundle ###

  php:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: 'mysql://app:!ChangeMe!@database:3306/app?serverVersion=8.0.32&charset=utf8mb4'
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - database
    ports:
      - "8000:8000"
    entrypoint: ["/usr/local/bin/docker-entrypoint.sh"]

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
